name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.7.20366.6
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack PlatformFramework
      run: dotnet pack src/PlatformFramework/PlatformFramework.csproj --output nuget-packages --configuration Release
    - name: Pack PlatformFramework.EFCore
      run: dotnet pack src/PlatformFramework.EFCore/PlatformFramework.EFCore.csproj --output nuget-packages --configuration Release
    - name: Pack PlatformFramework.EFCore.Identity
      run: dotnet pack src/PlatformFramework.EFCore.Identity/PlatformFramework.EFCore.Identity.csproj --output nuget-packages --configuration Release
    - name: Push to NuGet
      run: dotnet nuget push 'nuget-packages/*.nupkg' --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true

