name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack Dot
      run: dotnet pack src/Dot/Dot.csproj --output nuget-packages --configuration Release
    - name: Pack Dot.EFCore
      run: dotnet pack src/Dot.EFCore/Dot.EFCore.csproj --output nuget-packages --configuration Release
    - name: Pack Dot.Web.Admin
      run: dotnet pack src/Dot.Web.Admin/Dot.Web.Admin.csproj --output nuget-packages --configuration Release
    - name: Push to NuGet
      run: dotnet nuget push 'nuget-packages/*.nupkg' --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true

